### ISSUE TITLE
Cite and Comment all your code using javadoc

### ISSUE THREAD

**Issue by joshuaguinness** [samm82/Helping-The-Homeless#22]
This doesn't need to be done immediately but needs to be done before we hand it in so if you have nothing to do and a module is done, please do this

**Comment by joshuaguinness** [comment]
My code is done.

**Comment by joshuaguinness** [comment]
ADT's are done

**Comment by samm82** [comment]
Weight is done

**Comment by joshuaguinness** [comment]
Done. Javadoc for all methods are done!
