### ISSUE TITLE
Validation and Verification

### ISSUE THREAD

**Issue by joshuaguinness** [samm82/Helping-The-Homeless#25]
We will need some manual test cases of whether or not it finds addresses in Toronto, then some automated ones in finding the best shelter.

@samm82 I will leave you in charge of this but I can help out as well

**Comment by samm82** [comment]
It seems like the capacity isn't being weighted correctly - I'll double check that

**Comment by joshuaguinness** [comment]
Wrote test cases. Sam tested to make sure the weighting is done properly and output makes sense.
