### ISSUE TITLE
Review Design Specification Document

### ISSUE THREAD

**Issue by joshuaguinness** [samm82/Helping-The-Homeless#32]
Read over everything and ensure grammar, spelling, ideas, etc are good and consistent with what is supposed to be on it as defined in the final project pdf page 10-11. Don't worry about the formatting because I will be putting it all in a word document before submitting anyways.

Especially: 
- [x] Put your proper macid and student number
- [x] Ensure the table of contributions is accurate, add any contributions I missed
- [x] ~~The module breakdowns and description make sense and are accurate~~ (Covered in #24)

**Comment by samm82** [comment]
Now Josh just needs to format it and I need to submit it
